### ISSUE TITLE
Can we add a CNAME for an EC2 in Cloud Formation Template when using Confluent quick start template?

### ISSUE THREAD

**Issue by mickog** [aws-quickstart/quickstart-examples#2]
Hi,

Right now after creating using quickstart our Kafka services are only accessible through IP or a generate DNS name using the IP on it. We are thinking this is probably not good practice, since this service will eventually get updated and the IP will be changed.
 
We are thinking our services should respond by a proper DNS URL. I.E - "kafka-broker.dev.latam.exampledomain.com", "schema-registry.dev.latam.exampledomain.com". This prevents internal changes in applications that may be using those services.

If you are using the quick start CFT to start a cluster on AWS is it possible to give the Zookeeper, Schema Registry, Connectors, Rest endpoints and Broker ec2s a CNAME through the CFT? If the creation of the EC2 was done in the CFT then we could use its IP to create a CNAME but as I can’t see any instances being created in the quick start this may not be possible?
 
Much Appreciated
Michael

**Comment by vsnyc** [comment]
Issue, created in a wrong project.
