### ISSUE TITLE
Dead Link to Walkthrough in cloudformation-cross-account sample README

### ISSUE THREAD

**Issue by ptcrash** [aws-quickstart/quickstart-examples#22]
README for cloudformation-cross-account sample was last updated 2 years ago. README says:

> For a walkthrough on it's usage see this article

But the link to article appears to have never been valid. Is there a legit article we can link?

**Comment by davmayd** [comment]
The link is working for me. https://aws.amazon.com/blogs/infrastructure-and-automation/multiple-account-multiple-region-aws-cloudformation/
